In [1]:
#importing libraries
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler,MinMaxScaler,LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report,confusion_matrix,f1_score

In [2]:
#load the dataset
data=pd.read_csv("datasets to work with/iris.csv")
data.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [3]:
#deciding features and output
X=data.drop("species",axis=1)
y=data["species"]
y.head()

0    setosa
1    setosa
2    setosa
3    setosa
4    setosa
Name: species, dtype: object

In [4]:
#train test split
X_train,X_test,y_train,y_test=train_test_split(X,y, train_size=0.8, test_size=0.2)

In [5]:
#calling the model
model=LogisticRegression()

In [6]:
#Train the model
model.fit(X_train,y_train)

LogisticRegression()

In [7]:
#predict the model
y_pred=model.predict(X_test)

In [8]:
#evaluating the model
print("classification report is \n",classification_report(y_test,y_pred))
print("The confusion matrix is \n", confusion_matrix(y_test,y_pred))

classification report is 
               precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      0.90      0.95        10
   virginica       0.91      1.00      0.95        10

    accuracy                           0.97        30
   macro avg       0.97      0.97      0.97        30
weighted avg       0.97      0.97      0.97        30

The confusion matrix is 
 [[10  0  0]
 [ 0  9  1]
 [ 0  0 10]]


E:\vs code software\python\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


ValueError: pos_label=1 is not a valid label. It should be one of ['set', 'setosa']